# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseFlutter@0
  inputs:
    version: 'stable'

- script: flutter pub get
  displayName: 'Install dependencies'

- script: flutter analyze
  displayName: 'Analyze code'

- script: flutter test
  displayName: 'Run tests'

- script: flutter build apk
  displayName: 'Build APK'
